name: Reusable - Shell script check

on:
  workflow_call:

jobs:
  shell-script-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Install shell check
        run: wget -qO- "https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz" | tar -xJv

      - name: Run shellcheck
        run: find -name '*.sh' | xargs shellcheck-stable/shellcheck --format=gcc
