name: Reusable - Misspell check

on:
  workflow_call:

jobs:
  misspell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Install misspell
        run: |
          curl -L -o install-misspell.sh \
               https://raw.githubusercontent.com/client9/misspell/master/install-misspell.sh
          sh ./install-misspell.sh

      - name: Run misspell
        run: |
          find . -type f \
                 -not -path './licenses/*' \
               | xargs bin/misspell -error
